openapi: 3.0.0
info:
  version: "0.1.0"
  title: "Messenger Backend"
servers:
  - url: "localhost:8081"
paths:
  /users/{username}:
    put:
      summary: Signup new user
      operationId: signup
      security: []
      tags:
        - auth
      parameters:
        - $ref: "#/components/parameters/username"
      requestBody:
        description: User Info
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      responses:
        "200":
          description: "Signup is successfull"
        "409":
          description: "Username is already registered"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{username}/session/:
    put:
      summary: Signin user
      operationId: signin
      security: []
      tags:
        - auth
      parameters:
        - $ref: "#/components/parameters/username"
      requestBody:
        description: User Session
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  minLength: 8
      responses:
        "200":
          description: User session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        "403":
          description: Access denied

  /chat/users:
    get:
      summary: List of users in the chat
      tags:
        - chat
      security: 
        - auth: [] 
      responses:
        "200":
          description: List of active users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"
        "403":
          description: Access denied

components:
  parameters:
    username:
      in: path
      name: username
      schema:
        type: string
        minLength: 2
      required: true
      example: john
      description:
        Username is used to uniquely identify a user within the system.
        It could only contain alphanumeric characters.
  schemas:
    UserInfo:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
    UserList:
      type: array
      items:
        type: object
        properties:
          username:
            type: string
            example: john
          status:
            $ref: "#/components/schemas/Status"
          self:
            type: boolean
        required:
          - username
          - status
    Status:
      type: string
      enum:
        - online
        - away
    Session:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          format: jwt

    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
            example: Internal Server Error
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

